name: Update Data Danantara Otomatis
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: 
permissions:
  contents: write # Wajib untuk push data
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install yfinance pandas lxml
      - run: python update_data.py
      - run: |
          git config --global user.name 'Danantara-Bot'
          git config --global user.email 'bot@danantara.go.id'
          git add dataset.json
          git commit -m "Update Market: $(date)" || exit 0
          git push